version: '2.2'

services:
 server:
   build: .
   restart: "unless-stopped"
   environment:
     - DATABASE_URL=postgres://postgres@postgres:5432/postgres
   depends_on:
     - postgres
   ports:
     - 5000:5000
 postgres:
   image: postgres:12
   container_name: postgres
   hostname: postgres
   restart: always
   privileged: true
   volumes:
     - vl-postgres-data:/var/lib/postgresql/data
   expose:
     - 5432
   environment:
     POSTGRES_HOST_AUTH_METHOD: trust
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: dchat
   healthcheck:
     test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
     interval: 10s
     timeout: 5s
     retries: 5
 minio:
   image: minio/minio:latest
   container_name: minio
   hostname: minio
   restart: always
   privileged: true
   volumes:
     - vl-minio-data:/data
   environment:
     MINIO_ACCESS_KEY: minio
     MINIO_SECRET_KEY: minio123
   ports:
     - 9000:9000
   command: server /data
   healthcheck:
     test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
     interval: 30s
     timeout: 20s
     retries: 3

volumes:
  vl-postgres-data:
  vl-minio-data:
