export const DateTimeFormatInfo = {
  STANDARD_DATE: 'YYYY-MM-DD',
  STANDARD_TIME: 'YYYY-MM-DD HH:mm:ss',
  STANDARD_SHORT_TIME: 'YYYY-MM-DD HH:mm',
  VN_DATE: 'DD/MM/YYYY',
  VN_DATETIME: 'DD/MM/YYYY HH:mm:ss',
  VN_SHORT_DATETIME: 'DD/MM/YYYY HH:mm',
  CHART_SHORT_DATETIME: 'HH:mm DD/MM/YYYY',
  CHART_SHORT_DATE: 'HH:mm DD/MM/YY',
  VN_ISO_DATETIME: 'DD-MM-YYYY',
  REPORT_STANDARD_DATE: 'YYYYMMDD',
};
